### ISSUE TITLE
how to start naiveproxy with v2rayn

### ISSUE THREAD

**Issue by tpy2f0** [bolucat/naive#1]
Can you teach me how to start naiveproxy with v2rayn，I can not find any turials about this and I do not have config files

**Comment by bolucat** [comment]
Hi, it seems that v2rayN still has some bugs when using naiveproxy (Cannot set system proxy when  handling naiveproxy traffic). So please wait for someone to fix that (And for now use naiveproxy with Clash / Windows bat is still a good choice)

Regards

**Comment by bolucat** [comment]
> Can you teach me how to start naiveproxy with v2rayn，I can not find any turials about this and I do not have config files

v2rayN works fine in the latest pre-release [5.18](https://github.com/2dust/v2rayN/releases/tag/5.18), please check the tutor written in [Readme](https://github.com/bolucat/naive/blob/main/README.md) to set up v2rayN
