### ISSUE TITLE
Client docker image seems to miss depenencies

### ISSUE THREAD

**Issue by qingmuhy** [bolucat/naive#3]
When I run the client docker on my Server with ARMV8 architecture, I get the following error.

/usr/bin/naive: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/bin/naive)

I start with the command below

 `docker run --network host --name naiveproxy -v /******/naiveproxy:/etc/naiveproxy --restart=always -d pocat/naiveproxy:client`

I don't particularly understand the technical details. If it's a problem with my settings, I'm sorry for the inconvenience.

**Comment by bolucat** [comment]
> When I run the client docker on my Server with ARMV8 architecture, I get the following error.
> 
> /usr/bin/naive: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/bin/naive)
> 
> I start with the command below
> 
> `docker run --network host --name naiveproxy -v /******/naiveproxy:/etc/naiveproxy --restart=always -d pocat/naiveproxy:client`
> 
> I don't particularly understand the technical details. If it's a problem with my settings, I'm sorry for the inconvenience.

Sorry, but I don't have any device with ARMv8 architecture to test that docker image, device with ARM architecture is way complicated than x86_64, and it has much more discrepancies among those architectures. I have tested the client image on x86_64 device, and it works well, I don't have any ideas to fix that. I recommand you to directly use the binary from author's build : [https://github.com/klzgrad/naiveproxy/releases/download/v106.0.5249.91-1/naiveproxy-v106.0.5249.91-1-linux-arm64.tar.xz](https://github.com/klzgrad/naiveproxy/releases/download/v106.0.5249.91-1/naiveproxy-v106.0.5249.91-1-linux-arm64.tar.xz), and write a systemd service profile to run that binary.

**Comment by qingmuhy** [comment]
I have found the problem. The GLIBC version of my machine is too low. Either upgrading GLIBC or compiling NaiveProxy myself can solve this error.

**Comment by bolucat** [comment]
> I have found the problem. The GLIBC version of my machine is too low. Either upgrading GLIBC or compiling NaiveProxy myself can solve this error.

OK, I will close this issue, have a nice day
