### ISSUE TITLE
Error run ./caddy validate Caddyfile

### ISSUE THREAD

**Issue by Pedisx** [bolucat/naive#5]
this error ==> ./caddy validate Caddyfile
2023/04/18 22:03:52.850 INFO    using adjacent Caddyfile
Error: adapting config using caddyfile: automation policy from site block is also default/catch-all policy because of key without hostname, and the two are in conflict: []certmagic.Issuer(nil) != []certmagic.Issuer{(*caddytls.ACMEIssuer)(0xc00033da40), (*caddytls.ZeroSSLIssuer)(0xc0001e1440)}

AND this Caddyfile ==>

{
  admin off
  log {
      output file /var/log/caddy/access.log
      level INFO
  }
  servers :2083 {
      protocols h1 h2 h3
  }
}

:2053 {
  redir https://{host}{uri} permanent
}

:2083, domain.com  #Modify to your domain
tls none@email.com  #Modify to your email address
route {
  forward_proxy {
      basic_auth pedram pedram56113  #Modify to your user name and password
      hide_ip
      hide_via
      probe_resistance secret.localhost
  }
  file_server {
      root /var/www/html
  }
}

you can help me? :)

**Comment by bolucat** [comment]
> this error ==> ./caddy validate Caddyfile 2023/04/18 22:03:52.850 INFO using adjacent Caddyfile Error: adapting config using caddyfile: automation policy from site block is also default/catch-all policy because of key without hostname, and the two are in conflict: []certmagic.Issuer(nil) != []certmagic.Issuer{(*caddytls.ACMEIssuer)(0xc00033da40), (*caddytls.ZeroSSLIssuer)(0xc0001e1440)}
> 
> AND this Caddyfile ==>
> 
> { admin off log { output file /var/log/caddy/access.log level INFO } servers :2083 { protocols h1 h2 h3 } }
> 
> :2053 { redir https://{host}{uri} permanent }
> 
> :2083, domain.com #Modify to your domain tls [none@email.com](mailto:none@email.com) #Modify to your email address route { forward_proxy { basic_auth pedram pedram56113 #Modify to your user name and password hide_ip hide_via probe_resistance secret.localhost } file_server { root /var/www/html } }
> 
> you can help me? :)

It's wired, why don't you use the standard HTTP and HTTPS port (80 and 443), but if you want to customize the port, you have to add some global options, otherwise errors will occur, the config should be:
```bash
{
	http_port 2053
	https_port 2083
	admin off
	log {
		output file /var/log/caddy/access.log
		level INFO
	}
	servers :2083 {
		protocols h1 h2 h3
	}
}

:2053 {
	redir https://{host}{uri} permanent
}

:2083, domain.com #Modify to your domain
tls none@email.com #Modify to your email address
route {
	forward_proxy {
		basic_auth pedram pedram56113 #Modify to your user name and password
		hide_ip
		hide_via
		probe_resistance secret.localhost
	}
	file_server {
		root /var/www/html
	}
}
```
This config should pass the validation, have a try

**Comment by Pedisx** [comment]
No problem, just show me this warning, I'm going to close this issue thank you for help


> ./caddy validate Caddyfile

```
2023/04/19 06:25:23.618 INFO    using adjacent Caddyfile
2023/04/19 06:25:23.629 WARN    Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies    {"adapter": "caddyfile", "file": "Caddyfile", "line": 2}
2023/04/19 06:25:23.631 INFO    redirected default logger       {"from": "stderr", "to": "/var/log/caddy/access.log"}
Valid configuration
```

**Comment by Pedisx** [comment]
> access.log 
```
{"level":"error","ts":1681885831.3949947,"logger":"http.acme_client","msg":"challenge failed","identifier":"ssoss.art","challenge_type":"http-01","problem":{"type":"","title":"","detail":"","instance":"","subproblems":[]}}
{"level":"error","ts":1681885831.395045,"logger":"http.acme_client","msg":"validating authorization","identifier":"ssoss.art","problem":{"type":"","title":"","detail":"","instance":"","subproblems":[]},"order":"https://acme.zerossl.com/v2/DV90/order/KA9lleRNe4QFWCJACyGf1Q","attempt":1,"max_attempts":3}
{"level":"error","ts":1681885831.3950818,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"ssoss.art","issuer":"acme.zerossl.com-v2-DV90","error":"HTTP 0  - "}
{"level":"error","ts":1681885831.3951342,"logger":"tls.obtain","msg":"will retry","error":"[ssoss.art] Obtain: [ssoss.art] solving challenge: ssoss.art: [ssoss.art] authorization failed: HTTP 0  -  (ca=https://acme.zerossl.com/v2/DV90)","attempt":5,"retrying_in":600,"elapsed":659.689695254,"max_duration":2592000}
2023/04/19 06:34:22.254 warn    http    server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server {"server_name": "srv0", "http_port": 2053}
2023/04/19 06:34:22.256 info    http    server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv1", "https_port": 2083}
2023/04/19 06:34:22.256 info    http    enabling automatic HTTP->HTTPS redirects        {"server_name": "srv1"}
2023/04/19 06:34:22.256 info    http.handlers.forward_proxy     Secret domain used to connect to proxy: secret.localhost
2023/04/19 06:34:22.259 info    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0003ed730"}
2023/04/19 06:34:22.259 info    tls.cache.maintenance   stopped background certificate maintenance      {"cache": "0xc0003ed730"}
```

**Comment by bolucat** [comment]
> > access.log
> 
> ```
> {"level":"error","ts":1681885831.3949947,"logger":"http.acme_client","msg":"challenge failed","identifier":"ssoss.art","challenge_type":"http-01","problem":{"type":"","title":"","detail":"","instance":"","subproblems":[]}}
> {"level":"error","ts":1681885831.395045,"logger":"http.acme_client","msg":"validating authorization","identifier":"ssoss.art","problem":{"type":"","title":"","detail":"","instance":"","subproblems":[]},"order":"https://acme.zerossl.com/v2/DV90/order/KA9lleRNe4QFWCJACyGf1Q","attempt":1,"max_attempts":3}
> {"level":"error","ts":1681885831.3950818,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"ssoss.art","issuer":"acme.zerossl.com-v2-DV90","error":"HTTP 0  - "}
> {"level":"error","ts":1681885831.3951342,"logger":"tls.obtain","msg":"will retry","error":"[ssoss.art] Obtain: [ssoss.art] solving challenge: ssoss.art: [ssoss.art] authorization failed: HTTP 0  -  (ca=https://acme.zerossl.com/v2/DV90)","attempt":5,"retrying_in":600,"elapsed":659.689695254,"max_duration":2592000}
> 2023/04/19 06:34:22.254 warn    http    server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server {"server_name": "srv0", "http_port": 2053}
> 2023/04/19 06:34:22.256 info    http    server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv1", "https_port": 2083}
> 2023/04/19 06:34:22.256 info    http    enabling automatic HTTP->HTTPS redirects        {"server_name": "srv1"}
> 2023/04/19 06:34:22.256 info    http.handlers.forward_proxy     Secret domain used to connect to proxy: secret.localhost
> 2023/04/19 06:34:22.259 info    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0003ed730"}
> 2023/04/19 06:34:22.259 info    tls.cache.maintenance   stopped background certificate maintenance      {"cache": "0xc0003ed730"}
> ```

It shows that caddy cannot automatically get a certificate because you don't use a standard HTTPS port (like 443), you can get a certificate by [acme.sh](https://github.com/acmesh-official/acme.sh#1-how-to-install) and modify the config like this : (assuming you put the certificate file in `/etc/my_cert/cert.pem` and put the key file in `/etc/my_cert/key.pem`)
```bash
{
	http_port 2053
	https_port 2083
	admin off
	log {
		output file /var/log/caddy/access.log
		level INFO
	}
	servers :2083 {
		protocols h1 h2 h3
	}
}

:2053 {
	redir https://{host}{uri} permanent
}

:2083, domain.com #Modify to your domain
tls /etc/my_cert/cert.pem /etc/my_cert/key.pem #Modify to your certificate and key location
route {
	forward_proxy {
		basic_auth pedram pedram56113 #Modify to your user name and password
		hide_ip
		hide_via
		probe_resistance secret.localhost
	}
	file_server {
		root /var/www/html
	}
}
```

**Comment by Pedisx** [comment]
It's better to run with the default ports, it's hard like this
:)

**Comment by bolucat** [comment]
> It's better to run with the default ports, it's hard like this :)

Yes, and if everything's fine, I will close this issue, have a nice day
