### ISSUE TITLE
pocat/naiveproxy image doesn't seem to contain layer4, but description page mentions it

### ISSUE THREAD

**Issue by licryle** [bolucat/naive#6]
https://hub.docker.com/r/pocat/naiveproxy mentions the image container caddy-l4 module, however it doesn't seem to be the case as a config using layer4 will result in:
naiveproxy    | Error: adapting config using caddyfile: /etc/naiveproxy/Caddyfile:15: unrecognized global option: layer4

A local download from https://caddyserver.com/download?package=github.com%2Fmholt%2Fcaddy-l4 supports the layer4 option.

**Comment by bolucat** [comment]
> https://hub.docker.com/r/pocat/naiveproxy mentions the image container caddy-l4 module, however it doesn't seem to be the case as a config using layer4 will result in: naiveproxy | Error: adapting config using caddyfile: /etc/naiveproxy/Caddyfile:15: unrecognized global option: layer4
> 
> A local download from https://caddyserver.com/download?package=github.com%2Fmholt%2Fcaddy-l4 supports the layer4 option.

Sorry about that, it's an [upstream issue](https://github.com/mholt/caddy-l4/issues/227) caused this error, I have built caddy with latest layer4 module, try to pull latest one

**Comment by licryle** [comment]
No problem - thank you!

The latest is fixed, however... the latest-uot seems to reject all requests with {"level":"error","ts":1724752002.9690328,"logger":"http.log.error","msg":"ResponseWriter doesn't implement http.Flusher","request": ... }

I can do without, but if you can repro, might be worth a look.

Thanks again!

**Comment by bolucat** [comment]
> No problem - thank you!
> 
> The latest is fixed, however... the latest-uot seems to reject all requests with {"level":"error","ts":1724752002.9690328,"logger":"http.log.error","msg":"ResponseWriter doesn't implement http.Flusher","request": ... }
> 
> I can do without, but if you can repro, might be worth a look.
> 
> Thanks again!

As you can see, [Uot](https://github.com/SagerNet/UoT) has been deprecated and nothing update since 2 years ago, I just keep this variant until someday Caddy can't compatible with it. The original Author [nekohasekai](https://github.com/nekohasekai) now focus on the new project [Sing-box](https://github.com/SagerNet/sing-box), if you wanna a try, just read sing-box docs.
